name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: fedora-monitor
          target: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu
          tar: unix
          zip: none
          token: ${{ secrets.GITHUB_TOKEN }}
